void main () {

    try {
        stoi("abc");
    }
    catch{
        print("ERROR");
    }

}