// The purpose of this file is to test a basic form of the Try Except, it should not produce an error and output nothing

void main () {

    try {
        stoi("1");
    }
    catch{
        print("ERROR");
    }

}