// The purpose of this file is to check code running before any runtime errors in my try catch
// should output ERROR

void main (){
    try {
        int i = 0;
        string s = "a";
        while(i < 2){
            i = i + 1;
            s = s + "b";
        }
        print(stoi(s));
    }
    catch {
        print("ERROR");
    }
}