// This file is to test the while structure within a try catch block, it should produce an error and output "ERROR"

void main () {

    try {
        int i = 0;
        string z = "a";
        while (i < 3){
            int k = stoi(z);
            i = i + 1;
        }
        print("DONE");
    }
    catch{
        print("ERROR");
    }
}